name: Lock Closed Issues

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: '14'
          # issue-comment: |
          #  This issue has been locked since it has been closed for more than 14 days.
          #
          #  If you have found a concrete bug or regression related to it, please open a new [bug report](https://github.com/openwebstacks/stacks-framework/new/choose) with a reproduction against the latest Stacks version. If you have any other comments you should join the chat at [Stacks Land](https://discord.ow3.org) or create a new [discussion](https://github.com/openwebstacks/stacks-framework).
          issue-lock-reason: ''
          process-only: issues
